id: DF8116A79
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-05T06:53:13+00:00'
last_modified: '2022-05-26T12:19:17.363576+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    588a:
      image_group_id: I1PD95882
      title: རྡོ་རྗེ་བྱབ་པའི་ལས་ཚོགས།
      total_pages: 1379
      order: 37
      base_file: 588a.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
