id: P83A454F9
initial_creation_type: ocr
source_metadata:
  volumes:
    a956a7a7642640e795f88972f37f7f94:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: རྡོ་རྗེ་བྱབ་པའི་ལས་ཚོགས།
      total_pages: 1379
      volume_number: 37
